// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/AddControlClass": {
            "post": {
                "description": "添加一个控制模块",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Control"
                ],
                "summary": "添加一个控制模块",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.AddControlClassReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.AddControlClassResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/AddControlDetail": {
            "post": {
                "description": "控制模块-键",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制模块-键"
                ],
                "summary": "添加一个控制模块-键",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.AddControlDetailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.AddControlDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/DeleteControlClass": {
            "post": {
                "description": "删除控制模块",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Control"
                ],
                "summary": "删除控制模块",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.DeleteControlClassReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.DeleteControlClassResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/DeleteControlDetail": {
            "post": {
                "description": "删除控制模块",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制模块-键"
                ],
                "summary": "删除控制模块",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.DeleteControlDetailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.DeleteControlDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/ExecControlDetail": {
            "post": {
                "description": "执行key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制模块-键"
                ],
                "summary": "执行key",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.ExecControlDetailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.ExecControlDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/GetControlClassInfo": {
            "post": {
                "description": "获取控制模块详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Control"
                ],
                "summary": "获取控制模块详情",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.GetControlClassInfoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.GetControlClassInfoResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/GetControlClassList": {
            "post": {
                "description": "获取控制模块列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Control"
                ],
                "summary": "获取控制模块列表",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.GetControlClassListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.GetControlClassListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/GetControlDetailList": {
            "post": {
                "description": "获取键列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制模块-键"
                ],
                "summary": "获取键列表",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.GetControlDetailListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.GetControlDetailListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/GetNowIconList": {
            "post": {
                "description": "获取当前图标列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取当前图标列表",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.GetNowIconListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.GetNowIconListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/GetNowMousePosition": {
            "post": {
                "description": "执行key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制模块-键"
                ],
                "summary": "获取当前鼠标位置",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.GetNowMousePositionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.GetNowMousePositionResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/GetSystemConfig": {
            "post": {
                "description": "获取当前系统设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取当前系统设置",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.GetSystemConfigReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.GetSystemConfigResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/SetSystemConfig": {
            "post": {
                "description": "设置当前系统设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "设置当前系统设置",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.SetSystemConfigReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.SetSystemConfigResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/StopControlDetail": {
            "post": {
                "description": "执行key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制模块-键"
                ],
                "summary": "停止执行key",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.StopControlDetailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.StopControlDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/UpdateControlClass": {
            "post": {
                "description": "更新控制模块",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Control"
                ],
                "summary": "更新控制模块",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.UpdateControlClassReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.UpdateControlClassResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/UpdateControlClassOrder": {
            "post": {
                "description": "更新控制顺序",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Control"
                ],
                "summary": "更新控制顺序",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.UpdateControlClassOrderReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.UpdateControlClassOrderResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/UpdateControlDetail": {
            "post": {
                "description": "更新控制模块",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制模块-键"
                ],
                "summary": "更新控制模块",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.UpdateControlDetailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.UpdateControlDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/UpdateControlDetailOrder": {
            "post": {
                "description": "更新控制顺序",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制模块-键"
                ],
                "summary": "更新控制顺序",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hd.UpdateControlDetailOrderReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "desc",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hd.GinResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hd.UpdateControlDetailOrderResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.ControlDetailExt": {
            "type": "object",
            "properties": {
                "control_type": {
                    "description": "1:快捷键，2：脚本 3：打开文件夹目录  4:打开网页",
                    "default": 0,
                    "allOf": [
                        {
                            "$ref": "#/definitions/config.ControlType"
                        }
                    ],
                    "example": 0
                },
                "detail_color": {
                    "type": "string",
                    "example": ""
                },
                "detail_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "detail_key": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.ControlKeyList"
                    }
                },
                "detail_name": {
                    "type": "string",
                    "example": ""
                },
                "detail_pic": {
                    "description": "图片",
                    "type": "string",
                    "example": ""
                },
                "detail_show_name": {
                    "description": "是否显示名称",
                    "type": "boolean"
                },
                "detail_show_type": {
                    "description": "1:color 2:图片",
                    "default": 0,
                    "allOf": [
                        {
                            "$ref": "#/definitions/config.ShowType"
                        }
                    ],
                    "example": 0
                },
                "path": {
                    "description": "目录或网页",
                    "type": "string",
                    "example": ""
                },
                "run_state": {
                    "description": "1:空闲 2：运行中",
                    "default": 0,
                    "allOf": [
                        {
                            "$ref": "#/definitions/config.RunState"
                        }
                    ],
                    "example": 0
                }
            }
        },
        "config.ControlDetailIdExt": {
            "type": "object",
            "properties": {
                "detail_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                }
            }
        },
        "config.ControlKeyList": {
            "type": "object",
            "properties": {
                "delay": {
                    "description": "当KeyType == 99时 使用 ms",
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "input": {
                    "description": "当KeyType == 2时 输入文本",
                    "type": "string",
                    "example": ""
                },
                "key": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/config.KKey"
                        }
                    ],
                    "example": ""
                },
                "key_list": {
                    "description": "当KeyType == 3时",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.KeyListT"
                    }
                },
                "key_press": {
                    "description": "当KeyType == 1时 1：单击 2：双击 3：按下 4：抬起",
                    "default": 0,
                    "allOf": [
                        {
                            "$ref": "#/definitions/config.PressType"
                        }
                    ],
                    "example": 0
                },
                "key_type": {
                    "description": "1 ：单键 2 ：文本 3 ：快捷键 4 :鼠标点击 5 :鼠标移动 6:鼠标滚轮 99：延迟",
                    "default": 0,
                    "allOf": [
                        {
                            "$ref": "#/definitions/config.KeyType"
                        }
                    ],
                    "example": 0
                },
                "point_x": {
                    "description": "当KeyType == 5时 使用 X",
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "point_y": {
                    "description": "当KeyType == 5时 使用 Y",
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "scroll": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "scroll_dir": {
                    "default": 0,
                    "allOf": [
                        {
                            "$ref": "#/definitions/config.KMouseScrollDir"
                        }
                    ],
                    "example": 0
                }
            }
        },
        "config.ControlListExt": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "control_name": {
                    "type": "string",
                    "example": ""
                },
                "control_order": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "detail_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.ControlDetailExt"
                    }
                },
                "key_height": {
                    "type": "string"
                },
                "key_width": {
                    "type": "string"
                }
            }
        },
        "config.ControlListIdT": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                }
            }
        },
        "config.ControlType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "x-enum-comments": {
                "ControlTypeExplorer": "3：打开文件夹目录",
                "ControlTypeNormal": "1:快捷键",
                "ControlTypeRunCmd": "4:打开cmd",
                "ControlTypeRunExe": "4:打开exe",
                "ControlTypeScript": "2：脚本",
                "ControlTypeWebsite": "4:打开网页"
            },
            "x-enum-varnames": [
                "ControlTypeNormal",
                "ControlTypeScript",
                "ControlTypeExplorer",
                "ControlTypeWebsite",
                "ControlTypeRunExe",
                "ControlTypeRunCmd"
            ]
        },
        "config.KKey": {
            "type": "string",
            "enum": [
                "` + "`" + `",
                "-",
                "=",
                "[",
                "]",
                "\\",
                ";",
                "'",
                ",",
                ".",
                "/",
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h",
                "i",
                "j",
                "k",
                "l",
                "m",
                "n",
                "o",
                "p",
                "q",
                "r",
                "s",
                "t",
                "u",
                "v",
                "w",
                "x",
                "y",
                "z",
                "A",
                "B",
                "C",
                "D",
                "E",
                "F",
                "G",
                "H",
                "I",
                "J",
                "K",
                "L",
                "M",
                "N",
                "O",
                "P",
                "Q",
                "R",
                "S",
                "U",
                "V",
                "W",
                "X",
                "Y",
                "Z",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "backspace",
                "delete",
                "enter",
                "tab",
                "esc",
                "escape",
                "up",
                "down",
                "right",
                "left",
                "home",
                "end",
                "pageup",
                "pagedown",
                "f1",
                "f2",
                "f3",
                "f4",
                "f5",
                "f6",
                "f7",
                "f8",
                "f9",
                "f10",
                "f11",
                "f12",
                "f13",
                "f14",
                "f15",
                "f16",
                "f17",
                "f18",
                "f19",
                "f20",
                "f21",
                "f22",
                "f23",
                "f24",
                "cmd",
                "lcmd",
                "rcmd",
                "alt",
                "lalt",
                "ralt",
                "ctrl",
                "lctrl",
                "rctrl",
                "control",
                "shift",
                "lshift",
                "rshift",
                "capslock",
                "space",
                "print",
                "printscreen",
                "insert",
                "menu",
                "audio_mute",
                "audio_vol_down",
                "audio_vol_up",
                "audio_play",
                "audio_stop",
                "audio_pause",
                "audio_prev",
                "audio_next",
                "audio_rewind",
                "audio_forward",
                "audio_repeat",
                "audio_random",
                "num0",
                "num1",
                "num2",
                "num3",
                "num4",
                "num5",
                "num6",
                "num7",
                "num8",
                "num9",
                "num_lock",
                "num.",
                "num+",
                "num-",
                "num*",
                "num/",
                "num_clear",
                "num_enter",
                "num_equal",
                "lights_mon_up",
                "lights_mon_down",
                "lights_kbd_toggle",
                "lights_kbd_up",
                "lights_kbd_down",
                "left",
                "right",
                "wheel"
            ],
            "x-enum-comments": {
                "AudioForward": "Linux only",
                "AudioMute": "Mute the volume",
                "AudioNext": "Next Track",
                "AudioPrev": "Previous Track",
                "AudioRandom": "Linux only",
                "AudioRepeat": "Linux only",
                "AudioRewind": "Linux only",
                "AudioVolDown": "Lower the volume",
                "AudioVolUp": "Increase the volume",
                "Cmd": "is the \"win\" key for windows",
                "Down": "Down arrow key",
                "Lalt": "left alt",
                "Lcmd": "left command",
                "Lctrl": "left ctrl",
                "Left": "Left arrow key",
                "LightsKbdToggle": "Toggle keyboard backlight on/off\t\tNo Windows support",
                "LightsKbdUp": "Turn up keyboard backlight brightness\tNo Windows support",
                "LightsMonDown": "Turn down monitor brightness\t\tNo Windows support",
                "LightsMonUp": "Turn up monitor brightness\t\t\tNo Windows support",
                "Lshift": "left shift",
                "Menu": "Windows only",
                "Num0": "numpad 0",
                "Printscreen": "No Mac support",
                "Ralt": "right alt",
                "Rcmd": "right command",
                "Rctrl": "right ctrl",
                "Right": "Right arrow key",
                "Rshift": "right shift",
                "Up": "Up arrow key"
            },
            "x-enum-varnames": [
                "Spec0",
                "Spec1",
                "Spec2",
                "Spec3",
                "Spec4",
                "Spec5",
                "Spec6",
                "Spec7",
                "Spec8",
                "Spec9",
                "Spec10",
                "KeyA",
                "KeyB",
                "KeyC",
                "KeyD",
                "KeyE",
                "KeyF",
                "KeyG",
                "KeyH",
                "KeyI",
                "KeyJ",
                "KeyK",
                "KeyL",
                "KeyM",
                "KeyN",
                "KeyO",
                "KeyP",
                "KeyQ",
                "KeyR",
                "KeyS",
                "KeyT",
                "KeyU",
                "KeyV",
                "KeyW",
                "KeyX",
                "KeyY",
                "KeyZ",
                "CapA",
                "CapB",
                "CapC",
                "CapD",
                "CapE",
                "CapF",
                "CapG",
                "CapH",
                "CapI",
                "CapJ",
                "CapK",
                "CapL",
                "CapM",
                "CapN",
                "CapO",
                "CapP",
                "CapQ",
                "CapR",
                "CapS",
                "CapU",
                "CapV",
                "CapW",
                "CapX",
                "CapY",
                "CapZ",
                "Key0",
                "Key1",
                "Key2",
                "Key3",
                "Key4",
                "Key5",
                "Key6",
                "Key7",
                "Key8",
                "Key9",
                "Backspace",
                "Delete",
                "Enter",
                "Tab",
                "Esc",
                "Escape",
                "Up",
                "Down",
                "Right",
                "Left",
                "Home",
                "End",
                "Pageup",
                "Pagedown",
                "F1",
                "F2",
                "F3",
                "F4",
                "F5",
                "F6",
                "F7",
                "F8",
                "F9",
                "F10",
                "F11",
                "F12",
                "F13",
                "F14",
                "F15",
                "F16",
                "F17",
                "F18",
                "F19",
                "F20",
                "F21",
                "F22",
                "F23",
                "F24",
                "Cmd",
                "Lcmd",
                "Rcmd",
                "Alt",
                "Lalt",
                "Ralt",
                "Ctrl",
                "Lctrl",
                "Rctrl",
                "Control",
                "Shift",
                "Lshift",
                "Rshift",
                "Capslock",
                "Space",
                "Print",
                "Printscreen",
                "Insert",
                "Menu",
                "AudioMute",
                "AudioVolDown",
                "AudioVolUp",
                "AudioPlay",
                "AudioStop",
                "AudioPause",
                "AudioPrev",
                "AudioNext",
                "AudioRewind",
                "AudioForward",
                "AudioRepeat",
                "AudioRandom",
                "Num0",
                "Num1",
                "Num2",
                "Num3",
                "Num4",
                "Num5",
                "Num6",
                "Num7",
                "Num8",
                "Num9",
                "NumLock",
                "NumDecimal",
                "NumPlus",
                "NumMinus",
                "NumMul",
                "NumDiv",
                "NumClear",
                "NumEnter",
                "NumEqual",
                "LightsMonUp",
                "LightsMonDown",
                "LightsKbdToggle",
                "LightsKbdUp",
                "LightsKbdDown",
                "MouseLeft",
                "MouseRight",
                "MouseWheel"
            ]
        },
        "config.KMouseScrollDir": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "MouseScrollUp",
                "MouseScrollDown",
                "MouseScrollLeft",
                "MouseScrollRight"
            ]
        },
        "config.KeyListT": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "key": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/config.KKey"
                        }
                    ],
                    "example": ""
                }
            }
        },
        "config.KeyType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5,
                6,
                99
            ],
            "x-enum-comments": {
                "KeyTypeDefault": "单键",
                "KeyTypeDelay": "延迟",
                "KeyTypeMouse": "鼠标点击",
                "KeyTypeMouseMove": "鼠标移动",
                "KeyTypeMouseScroll": "鼠标滚轮",
                "KeyTypeShortcutKey": "快捷键",
                "KeyTypeText": "文本"
            },
            "x-enum-varnames": [
                "KeyTypeDefault",
                "KeyTypeText",
                "KeyTypeShortcutKey",
                "KeyTypeMouse",
                "KeyTypeMouseMove",
                "KeyTypeMouseScroll",
                "KeyTypeDelay"
            ]
        },
        "config.PressType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4
            ],
            "x-enum-comments": {
                "PressTypeClick": "单击",
                "PressTypeDoubleClick": "双击",
                "PressTypePressDown": "按下",
                "PressTypePressUp": "抬起"
            },
            "x-enum-varnames": [
                "PressTypeClick",
                "PressTypeDoubleClick",
                "PressTypePressDown",
                "PressTypePressUp"
            ]
        },
        "config.RunState": {
            "type": "integer",
            "enum": [
                1,
                2
            ],
            "x-enum-comments": {
                "RunStateFree": "空闲",
                "RunStateRunning": "运行中"
            },
            "x-enum-varnames": [
                "RunStateFree",
                "RunStateRunning"
            ]
        },
        "config.ShowType": {
            "type": "integer",
            "enum": [
                1,
                2
            ],
            "x-enum-varnames": [
                "ShowTypeColor",
                "ShowTypePic"
            ]
        },
        "hd.AddControlClassReq": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "control_name": {
                    "type": "string",
                    "example": ""
                },
                "control_order": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "key_height": {
                    "type": "string"
                },
                "key_width": {
                    "type": "string"
                }
            }
        },
        "hd.AddControlClassResp": {
            "type": "object"
        },
        "hd.AddControlDetailReq": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "detail": {
                    "$ref": "#/definitions/config.ControlDetailExt"
                }
            }
        },
        "hd.AddControlDetailResp": {
            "type": "object"
        },
        "hd.DeleteControlClassReq": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                }
            }
        },
        "hd.DeleteControlClassResp": {
            "type": "object"
        },
        "hd.DeleteControlDetailReq": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "detail_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                }
            }
        },
        "hd.DeleteControlDetailResp": {
            "type": "object"
        },
        "hd.ExecControlDetailReq": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "detail_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                }
            }
        },
        "hd.ExecControlDetailResp": {
            "type": "object"
        },
        "hd.GetControlClassInfoReq": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                }
            }
        },
        "hd.GetControlClassInfoResp": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "control_name": {
                    "type": "string",
                    "example": ""
                },
                "control_order": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "key_height": {
                    "type": "string"
                },
                "key_width": {
                    "type": "string"
                }
            }
        },
        "hd.GetControlClassListReq": {
            "type": "object"
        },
        "hd.GetControlClassListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.ControlListExt"
                    }
                }
            }
        },
        "hd.GetControlDetailListReq": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                }
            }
        },
        "hd.GetControlDetailListResp": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.ControlDetailExt"
                    }
                }
            }
        },
        "hd.GetNowIconListReq": {
            "type": "object"
        },
        "hd.GetNowIconListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/module.IconT"
                    }
                }
            }
        },
        "hd.GetNowMousePositionReq": {
            "type": "object"
        },
        "hd.GetNowMousePositionResp": {
            "type": "object",
            "properties": {
                "x": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "y": {
                    "type": "integer",
                    "default": 0
                }
            }
        },
        "hd.GetSystemConfigReq": {
            "type": "object"
        },
        "hd.GetSystemConfigResp": {
            "type": "object",
            "properties": {
                "is_scale": {
                    "description": "屏幕是否缩放",
                    "type": "boolean"
                },
                "run_ip": {
                    "description": "运行ip地址",
                    "type": "string",
                    "example": ""
                },
                "run_port": {
                    "description": "运行端口",
                    "type": "integer",
                    "default": 8080,
                    "example": 8080
                },
                "sound_open": {
                    "type": "boolean"
                }
            }
        },
        "hd.GinResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "msg": {
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/hd.STATE_CODE"
                }
            }
        },
        "hd.STATE_CODE": {
            "type": "integer",
            "enum": [
                9999,
                0,
                1
            ],
            "x-enum-comments": {
                "StateFailed": "失败",
                "StateOk": "成功",
                "StatePanic": "服务器崩溃"
            },
            "x-enum-varnames": [
                "StatePanic",
                "StateOk",
                "StateFailed"
            ]
        },
        "hd.SetSystemConfigReq": {
            "type": "object",
            "properties": {
                "is_scale": {
                    "description": "屏幕是否缩放",
                    "type": "boolean"
                },
                "run_ip": {
                    "description": "运行ip地址",
                    "type": "string",
                    "example": ""
                },
                "run_port": {
                    "description": "运行端口",
                    "type": "integer",
                    "default": 8080,
                    "example": 8080
                },
                "sound_open": {
                    "type": "boolean"
                }
            }
        },
        "hd.SetSystemConfigResp": {
            "type": "object"
        },
        "hd.StopControlDetailReq": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "detail_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                }
            }
        },
        "hd.StopControlDetailResp": {
            "type": "object"
        },
        "hd.UpdateControlClassOrderReq": {
            "type": "object",
            "properties": {
                "order_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.ControlListIdT"
                    }
                }
            }
        },
        "hd.UpdateControlClassOrderResp": {
            "type": "object"
        },
        "hd.UpdateControlClassReq": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "control_name": {
                    "type": "string",
                    "example": ""
                },
                "control_order": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "key_height": {
                    "type": "string"
                },
                "key_width": {
                    "type": "string"
                }
            }
        },
        "hd.UpdateControlClassResp": {
            "type": "object"
        },
        "hd.UpdateControlDetailOrderReq": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.ControlDetailIdExt"
                    }
                }
            }
        },
        "hd.UpdateControlDetailOrderResp": {
            "type": "object"
        },
        "hd.UpdateControlDetailReq": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "integer",
                    "default": 0,
                    "example": 0
                },
                "detail": {
                    "$ref": "#/definitions/config.ControlDetailExt"
                }
            }
        },
        "hd.UpdateControlDetailResp": {
            "type": "object"
        },
        "module.IconT": {
            "type": "object",
            "properties": {
                "icon_name": {
                    "type": "string"
                },
                "icon_path": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
